### ISSUE TITLE
Error with white space in filepath

### ISSUE THREAD

**Issue by bonsak** [jtomori/hou_bg_render#1]
Thank you so much for making this script. We are using Dropbox Business on some of our projects and it insists on inserting a white space character between "Dropbox" and our company name in the root of the file system.  We have not found a way to edit this.
Trying to use your script on files located in our Dropbox results in this error:

`Unknown file type F:/Racecar
Unable to open file: Dropbox/18055/3D/Elements/Characters/Crowds/agent-setup-04.hip`

The the actual file path is like this: `F:/Racecar Dropbox/18055/3D/Elements/Characters/Crowds/agent-setup-04.hip`

Is there a way to make your script work with paths that contains white space characters?
We are working on windows.

**Comment by jtomori** [comment]
Hi,
thanks for submitting a fix c7acb02

**Comment by bonsak** [comment]
Np :)
